version: '3.7'
services:
  python3:
    image: "experiment"
    container_name: "experiment"
    init: true
    user: "${USER_ID}:${GROUP_ID}"
    restart: always
    build: .
    working_dir: "/home/${USER_NAME}/"
    tty: true
    volumes:
      - ./:/home/${USER_NAME}/experiment/
    ports:
      - "${PORT}:${PORT}"
    build:
      context: .
      dockerfile: "${Dockerfile}"
      args:
        - USER_ID=${USER_ID}
        - USER_NAME=${USER_NAME}
    command: jupyter lab --ip=0.0.0.0 --no-browser --port=${PORT}

    # If you exec jupyter as root, you need --allow-root.
    # But I mapped UID to non root, so I don't need --allow-root.
    # command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
